### ISSUE TITLE
能否提供一个完整的详细的例程？

### ISSUE THREAD

**Issue by qinerg** [qiujiayu/AutoLoadCache-nutz#1]
看介绍感觉理念非常好，能否提供一个完整的基于 nutz 的例程，这样入起门来就会更轻松些了。
谢谢

**Comment by qiujiayu** [comment]
在这个工程的src/test目录中有例子，如果要详细了解AutoloadCache的使用，[https://github.com/qiujiayu/AutoLoadCache](https://github.com/qiujiayu/AutoLoadCache) 中有说明文档，还有基于Spring AOP的例子 [https://github.com/qiujiayu/cache-example](https://github.com/qiujiayu/cache-example)
