### ISSUE TITLE
缓存的表达式引擎能否不强依赖于spring?

### ISSUE THREAD

**Issue by qinerg** [qiujiayu/AutoLoadCache-nutz#2]
nutz本身可视为精简版的spring，但用 cache 的时候还是需要引一堆spring表达式的包。
是否可以对表达式引擎能否做一层抽像，nutz也自带了表达式引擎。或者直接使用 jdk 自带的 JavaScript 脚本引擎来做处理？

**Comment by Rekoe** [comment]
jdk 自带的 JavaScript 脚本引擎来做处理
支持用这种方式
另外 nutz 有针对autoloadcache的插件 你可以用原生的autoloadcache包 +nutz_autoloadcache 插件
@qinerg 
https://github.com/nutzam/nutzmore/tree/master/nutz-integration-autoloadcache

**Comment by qiujiayu** [comment]
autoloadcache 4.7版本已经增加这方面的扩展。

**Comment by qinerg** [comment]
赞！
